name: CI and README update

on:
  push:
    branches: [ "main" ]
    paths:
      - 'README.md' # Trigger only when README.md changes
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build_and_copy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      - name: Copy README to remote server
        uses: appleboy/scp-action@master
        with:
           host: ${{ secrets.178.62.244.94}}
           username: ${{ secrets.projects_user }}
           password: ${{ secrets.egd_idd_08G!}}
           port: ${{ secrets.22 }}
           source: "README.md"
           target: "/var/www/projects/218667660"

      - name: Update Trello card
        run: |
          # Your Trello API call here to update the corresponding card
          # For example, you can use curl to make a PUT request to Trello API
          # Make sure to replace placeholders with actual values
          curl --request PUT \
               --url 'https://api.trello.com/1/cards/${{ secrets.65f1a54754a403597b232ebc}}' \
               --header 'Authorization: Bearer ${{ secrets.ATATT3xFfGF0SQYwTrbqWM-30po9Rp6TrvmULRNZyoWdCoH3bbvAC9qoAHv1ZB-xFL0hp-qnJuN1_BnMLKznpMV5OAwsKNpKqsIHSv6swd2kteIce-A1OySh3nBO7c1uoKKY1QBwTchA75cKRy1uhTb9GqWtg17Rh2ha20a6AplfowNogy3rk1w=FDEDC92C}}' \
               --header 'Content-Type: application/json' \
               --data '{"desc": "Updated README.md file"}'
