name: CI and README update

on:
  push:
    branches: [ "main" ]
    paths:
      - 'README.md' # Trigger only when README.md changes
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build_and_copy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      - name: Copy README to remote server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "README.md"
          target: "/var/www/projects/218667660"
